# Development Environment for Cloud Run Jobs
version: '3.8'

services:
  # Example: Test extraction job locally
  extraction-job:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
    env_file:
      - .env
    environment:
      - ENVIRONMENT=local
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - ./src:/app/src
      - ./credentials.json:/app/credentials.json:ro
      - pipeline-data:/app/data
      - pipeline-logs:/app/logs
    command: ["python", "src/toltek/jobs/extraction/run_google_sheets.py"]
    profiles:
      - extraction

  # Example: Test transformation job locally  
  transformation-job:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
    env_file:
      - .env
    environment:
      - ENVIRONMENT=local
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - ./src:/app/src
      - ./credentials.json:/app/credentials.json:ro
      - pipeline-data:/app/data
      - pipeline-logs:/app/logs
    command: ["python", "src/toltek/jobs/transformation/run_dbt.py"]
    profiles:
      - transformation

  # Example: Test ML job locally
  ml-job:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
    env_file:
      - .env
    environment:
      - ENVIRONMENT=local
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - ./src:/app/src
      - ./credentials.json:/app/credentials.json:ro
      - pipeline-data:/app/data
      - pipeline-logs:/app/logs
    command: ["python", "src/toltek/jobs/ml/train_forecasting.py"]
    profiles:
      - ml

volumes:
  pipeline-data:
  pipeline-logs:

# Usage examples:
# docker-compose --profile extraction up   # Test extraction jobs
# docker-compose --profile transformation up # Test transformation jobs  
# docker-compose --profile ml up             # Test ML jobs